/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: Jackey&Design (https://sketchfab.com/1394725324zhang)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/apple-watch-s9-gps-1c7b938b3a8f4ea2b0026ecaa4887ed0
Title: Apple_Watch_S9_gps
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';
import { useThree } from '@react-three/fiber';
import ScrollTrigger from 'gsap/ScrollTrigger';


export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')

 


  return (
    <group {...props} dispose={null}>
      <group scale={0.5}>
        <mesh geometry={nodes.MLFNgqDqViRzFAG.geometry} material={materials.HUwkFDLqEFoTaxW} />
        <mesh geometry={nodes.BpzHTNsUQYccQZO.geometry} material={materials.LLmsxstJxVgNsnb} />
        <mesh geometry={nodes.nTQgANoyTueuTWO.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.bAKLNmPbIOnlFCh.geometry} material={materials.JoIbGRmJFdsSNYI} />
        <mesh geometry={nodes.nzegwylKXokNRsu.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.zqzfMzpOMmkwooz.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.NviWfdPIAuwGhuw.geometry} material={materials.kVaeXYFaJhdUARb} />
        <mesh geometry={nodes.fSjUqbzpOBClCkp.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.jsYOceOPookXogG.geometry} material={materials.riakWjRZAXAqWsu} />
        <mesh geometry={nodes.nFcRxfWEoAIgIJM.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.FRHeKieRtsuKFqI.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.ICiLfTgRKmVDURH.geometry} material={materials.kXCmZWmPBarbEsJ} />
        <mesh geometry={nodes.zWHRYuSXNrwKuOu.geometry} material={materials.tbZIZBblUmkrxKp} />
        <mesh geometry={nodes.lQWqZzniJdQEyQf_0.geometry} material={materials.LLmsxstJxVgNsnb} />
        <mesh geometry={nodes.lxGVWzQjohjPxnt.geometry} material={materials.XybRtJquThvOCqQ} />
        <mesh geometry={nodes.IhbCJvqLshKQhue.geometry} material={materials.MDljgHDjAwWtGGq} />
        <mesh geometry={nodes.dkRonzbxLCwjzkb.geometry} material={materials.WkKmICuLIpNbpaj} />
        <mesh geometry={nodes.FjtjvYUJdMYiQQw.geometry} material={materials.akMNLWSaXiEtqoo} />
        <mesh geometry={nodes.LCtXMkfUukutNIX.geometry} material={materials.SlELGRYBEUAqHzo} />
        <mesh geometry={nodes.zckGhJEDdcidEBl.geometry} material={materials.hKCSgbIkkiPrZbN} />
        <mesh geometry={nodes.JvxFZHlxSggEiWF.geometry} material={materials.WZBNGWfTxwcsSLf} />
        <mesh geometry={nodes.mEszvIfbdUjfuly.geometry} material={materials.jHJGJrQrsYkmgQj} />
        <mesh geometry={nodes.hvGrKGneRLvJuto.geometry} material={materials.HvwaINjHNhePohJ} />
        <mesh geometry={nodes.cJKoXSmaNEvYEoi.geometry} material={materials.MDljgHDjAwWtGGq} />
        <mesh geometry={nodes.JGPnreQDUYirYCY.geometry} material={materials.MDljgHDjAwWtGGq} />
        <mesh geometry={nodes.MsbPtksJZInzUhu.geometry} material={materials.GNjoSxTDopqKuIq} />
        <mesh geometry={nodes.FrRXehOiqNjIFAr.geometry} material={materials.GNjoSxTDopqKuIq} />
        <mesh geometry={nodes.qvShfmDCzhKDUQe.geometry} material={materials.GNjoSxTDopqKuIq} />
        <mesh geometry={nodes.NqTzDYBhJHwdKFO.geometry} material={materials.MPCGBHstQClgXwb} />
        <mesh geometry={nodes.xjJcyeocVcXUcrL.geometry} material={materials.gdQqldeaKRUzcOc} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
